name: jupyter-build

on:
- push

jobs:
  jupyter-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Build the books
      run: |
        shopt -s globstar
        TOTAL_ERRORS=0
        for nb in tutorials/**/*.ipynb; do
            jupyter-book build "$nb"
            grep -q '"output_type": "error"' "$nb" && echo "Found errors in $nb" && TOTAL_ERRORS=$(($TOTAL_ERRORS + 1))          
        done
        echo "$TOTAL_ERRORS total errors found"
        exit $TOTAL_ERRORS
        