name: jupyter-matrix
on: push
jobs:
  list-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls tutorials/**/*.ipynb | jq -R -s -c 'split("\n")[:-1]')"
  notebook:
    needs: list-notebooks
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-notebooks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - run: echo "NOTEBOOK=${{ matrix.manifest }}" >> $GITHUB_ENV

      - name: Build the books
        run: |
        echo "${{ env.NOTEBOOK }}"
        # TOTAL_ERRORS=0
        # jupyter nbconvert --to notebook --inplace --execute --allow-errors "${{ env.NOTEBOOK }}"
        # grep -q '"output_type": "error"' "${{ env.NOTEBOOK }}" && echo "Found errors in ${{ env.NOTEBOOK }}" && TOTAL_ERRORS=1
        # exit $TOTAL_ERRORS          